# Generated by Django 4.0.6 on 2022-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='log',
            field=models.BooleanField(default=True),
        ),
    ]
