# Generated by Django 4.0.6 on 2022-11-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_adminlogin_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminlogin',
            old_name='log',
            new_name='is_active',
        ),
    ]
